### ISSUE TITLE
SafePow is not used in SimpleParserHelper

### ISSUE THREAD

**Issue by marcin-golebiowski** [SpiceSharp/SpiceSharpBehavioral#12]
I will publish PR later today.

**Comment by svenboulanger** [comment]
I believe the issue is: do we want `SafePow()` in `SimpleParser`? It can't be used as a parser for components because it's not capable of calculating derivatives. The usecase for `SimpleParser` is completely different.

**Comment by marcin-golebiowski** [comment]
The reason I want it is that simulation for the netlist posted in #4 doesn't finish with the result but with "NaN"

**Comment by marcin-golebiowski** [comment]
With that change I have correct results  I believe.

**Comment by svenboulanger** [comment]
The example you linked to seems to use `ExpressionTreeDerivativeParser`. The other parser that would require `SafePow()` is `SimpleDerivativeParser`. I may be wrong, but I believe I implemented a "safe" pow() method for both of them.

**Comment by marcin-golebiowski** [comment]
In SpiceSharpParser I also use SimpleParser for initial values.

**Comment by svenboulanger** [comment]
Could you elaborate on that? How do you deal with custom variables, parameters, functions, etc.? What do you use the initial values for?

**Comment by marcin-golebiowski** [comment]
No problem but in the evening. 

/Marcin

**Comment by marcin-golebiowski** [comment]
I use SimpleParser for:

1) Getting list of variables from expressions. For example: 
R1 0 1 {a+b+c} . I need then to update value of property (besides behavioral components, there is second mechanism for property updates for other components)

2) Evaluating .IF clauses. For example:
.IF (a == 0)
.ENDIF

3) Evaluating values of custom functions.

**Comment by marcin-golebiowski** [comment]
@svenboulanger I've changed the SpiceSharpParser to use only one type of parser: SimpleDerivativeParser
