### ISSUE TITLE
Example for more complex circuit

### ISSUE THREAD

**Issue by DZychlinski** [SpiceSharp/SpiceSharpBehavioral#16]
Hi,

is it possible to get more advanced example on how to use SpiceSharpBehavioral with circuit like this one?

```
I_M 0 N1 0.025
X_entry1 N1 0 N2 entry_1
X_entry2 N1 0 N3 entry_2

.subckt entry_1 m_in m_out v_vel
Vmas m_in msx 0
Rmas msx msy 1e-6
Bxm msy m_out V={V(v_vel)*V(v_vel)/2.1}
Hmss mss 0 Vmas 1
Buv 0 v_vel I={(V(mss)/120)/(0.1)}
Ruv 0 v_vel 1
.ends

.subckt entry_2 m_in m_out v_vel
Vmas m_in msx 0
Rmas msx msy 1e-6
Bxm msy m_out V={V(v_vel)*V(v_vel)/2}
Hmss mss 0 Vmas 1
Buv 0 v_vel I={(V(mss)/120)/(0.1)}
Ruv 0 v_vel 1
.ends

.OP
.SAVE V(N1)
.end
```

I have it implemented partially like this (in simplified form), but I doubt that it is correct (considering I have two subcircuits):

```C#
private Circuit GetCircuit()
{
	var dc = 0.025;
	var result = new Circuit
	{
		new CurrentSource("I_M", "0", "N1", dc),
	};

	result.Merge(GetSubCircuit(1));
	result.Merge(GetSubCircuit(2));

	return result;
}

private Circuit GetSubCircuit(int circuitId)
{
	var bxmExpr = circuitId == 1 ? "V(v_vel)*V(v_vel)/2.1" : "V(v_vel)*V(v_vel)/2";
	var buvExpr = "(V(mss)/120)/(0.1)";

	var result = new Circuit
	{
		new VoltageSource($"Vmas{circuitId}", "N1", $"msx{circuitId}", 0),
		new Resistor($"Rmas{circuitId}", $"msx{circuitId}", $"msy{circuitId}", 1e-6),
		new BehavioralVoltageSource($"Bxm{circuitId}", $"msy{circuitId}", "0", bxmExpr),
		new CurrentControlledVoltageSource($"Hmss{circuitId}", $"mss{circuitId}", "0", $"Vmas{circuitId}", 1),
		new BehavioralCurrentSource($"Buv{circuitId}", "0",$"v_vel{circuitId}", buvExpr),
		new Resistor($"Ruv{circuitId}", "0", $"v_vel{circuitId}", 1),
	};

	return result;
}
```

Also, can I declare expressions for Bxm and Buv as strings or should I add calls to my custom functions (through Parser)?

**Comment by svenboulanger** [comment]
Hi!

I don't see anything particularly wrong with your way of implementing subcircuits. It is very similar to how all other Spice simulators will implement subcircuits. 

For subcircuits, usually the "local" nodes are given a path like "X1.N1", which is node N1 of subcircuit X1. Nested subcircuits can similarly generate paths like "X2.Xabc.X1.v_vel".
Local entities are usually given the same treatment, except that the first character is retained to be able to identify the type of component, like "RX1.Rload". This is not necessary in Spice#.

You can enter whatever expressions you want for behavioral sources. You can also define your own functions, but remember that you also have to implement their derivatives to make it work in simulations.
You may need to be a bit careful with squaring V(v_vel) though, because the result is not defined over all ranges (it is only possible to have positive currents). This may lead to impossible Circuits or convergence issues. If you use "pow(V(v_vel), 2)" instead, the default implementation will instead use an antisymmetric function that is defined and derivable over all ranges.

**Comment by DZychlinski** [comment]
Hi Sven!

I received permission to post the entire circuit that we need to test, so that it would be easier now to verify this (I initially wanted to make sure that our way of writing it is fine).
Here's the NetList for said circuit (simplified version of this is what I initially posted on SpiceSharpParser repo [here](https://github.com/SpiceSharp/SpiceSharpParser/issues/114)):
```
* Test circuit from Spice3f5
 
I_M 0 N1 0.025
X_entry1 N1 0 N2 entry_1
X_entry2 N1 0 N3 entry_2

.subckt entry_1 m_in m_out v_vel
Vmas m_in msx 0  
Rmas msx msy 1e-6
Bxm msy m_out V={((40*exp((-0.9)*ln(abs((V(v_vel))*0.0181818/6e-06)+1e-12))+90*exp(((-0.003))*ln(abs((0.0947059))))-80)*850*V(v_vel)*V(v_vel)/2)}
Hmss mss 0 Vmas 1
Buv 0 v_vel I={(V(mss)/850)/(0.1*0.01)}
Ruv 0 v_vel 1
.ends

.subckt entry_2 m_in m_out v_vel
Vmas m_in msx 0  
Rmas msx msy 1e-6
Bxm msy m_out V={((40*exp((-0.9)*ln(abs((V(v_vel))*0.0181818/6e-06)+1e-12))+90*exp(((-0.003))*ln(abs((0.105294))))-80)*850*V(v_vel)*V(v_vel)/2)}
Hmss mss 0 Vmas 1
buv 0 v_vel I={(V(mss)/850)/(0.1*0.01)}
Ruv 0 v_vel 1
.ends

.OP
.options abstol=1e-5
.end
```
And this is how we feed it into the Parser:
```C#
public class NetListParser
{
	public void Run()
	{
		var netlist = File.ReadAllText(@"path-to-above-netlist");

		var parser = new SpiceParser();
		var parseResult = parser.ParseNetlist(netlist);
		var spiceSharpModel = parseResult.SpiceSharpModel;

		var simulation = spiceSharpModel.Simulations.Single();
		simulation.ExportSimulationData += (sender, args) => { Print(args); };

		simulation.Run(spiceSharpModel.Circuit);
	}

	private void Print(ExportDataEventArgs args)
	{
		Console.WriteLine("N1 {0}", args.GetVoltage("N1"));
		Console.WriteLine("X_entry1.msx {0}", args.GetVoltage("X_entry1.msx"));
		Console.WriteLine("X_entry1.msy {0}", args.GetVoltage("X_entry1.msy"));
		Console.WriteLine("N2 {0}", args.GetVoltage("N2"));
		Console.WriteLine("X_entry1.mss {0}", args.GetVoltage("X_entry1.mss"));
		Console.WriteLine("X_entry2.msx {0}", args.GetVoltage("X_entry2.msx"));
		Console.WriteLine("X_entry2.msy {0}", args.GetVoltage("X_entry2.msy"));
		Console.WriteLine("N3 {0}", args.GetVoltage("N3"));
		Console.WriteLine("X_entry2.mss {0}", args.GetVoltage("X_entry2.mss"));
	}
}
```
We get correct results compared to BerkeleySpice (or at least those are very close to what we expect).
Now what we would like to do is to implement it in Spice# directly, without using SpiceSharpParser (although it's very useful in fast verification and comparison of results). As an example, we have this implementation:
```C#
public class SpiceParserSample
{
	public void Run()
	{
		var op = new OP("op");
		op.Configurations.Get<BaseConfiguration>().AbsoluteTolerance = 1E-5;
		op.ExportSimulationData += (sender, args) => { Print(args); };
		op.Run(GetCircuit());
	}

	private void Print(ExportDataEventArgs args)
	{
		Console.WriteLine("N1 {0}", args.GetVoltage("N1"));
		Console.WriteLine("X_entry1.msx {0}", args.GetVoltage("msx1"));
		Console.WriteLine("X_entry1.msy {0}", args.GetVoltage("msy1"));
		Console.WriteLine("N2 {0}", args.GetVoltage("v_vel1"));
		Console.WriteLine("X_entry1.mss {0}", args.GetVoltage("mss1"));
		Console.WriteLine("X_entry2.msx {0}", args.GetVoltage("msx2"));
		Console.WriteLine("X_entry2.msy {0}", args.GetVoltage("msy2"));
		Console.WriteLine("N3 {0}", args.GetVoltage("v_vel2"));
		Console.WriteLine("X_entry2.mss {0}", args.GetVoltage("mss2"));
	}

	private Circuit GetCircuit()
	{
		var dc = 0.025;
		var result = new Circuit
		{
			new CurrentSource("I_M", "0", "N1", dc),
		};

		result.Merge(GetSubCircuit(1));
		result.Merge(GetSubCircuit(2));

		return result;
	}

	private Circuit GetSubCircuit(int circuitId)
	{
		var bxmExpr = circuitId == 1
			? "((40*Exp((-0.9)*Log(Abs((V(v_vel1))*0.0181818/6e-06)+1e-12))+90*Exp(((-0.003))*Log(Abs((0.0947059))))-80)*850*V(v_vel1)*V(v_vel1)/2)"
			: "((40*Exp((-0.9)*Log(Abs((V(v_vel2))*0.0181818/6e-06)+1e-12))+90*Exp(((-0.003))*Log(Abs((0.105294))))-80)*850*V(v_vel2)*V(v_vel2)/2)";
		var buvExpr = "(V(mss)/850)/(0.1*0.01)";

		var result = new Circuit
		{
			new VoltageSource($"Vmas{circuitId}", "N1", $"msx{circuitId}", 0),
			new Resistor($"Rmas{circuitId}", $"msx{circuitId}", $"msy{circuitId}", 1e-6),
			new BehavioralVoltageSource($"Bxm{circuitId}", $"msy{circuitId}", "0", bxmExpr),
			new CurrentControlledVoltageSource($"Hmss{circuitId}", $"mss{circuitId}", "0", $"Vmas{circuitId}", 1),
			new BehavioralCurrentSource($"Buv{circuitId}", "0",$"v_vel{circuitId}", buvExpr),
			new Resistor($"Ruv{circuitId}", "0", $"v_vel{circuitId}", 1),
		};

		return result;
	}
}
```
`Print` outputs nodes with the same name, just for easier comparison.

Variable `bxmExpr` was also adjusted a little bit to use correct names and capitalization of functions that SpiceSharp expects.

The issue we are facing is that SpiceSharpParser can parse original circuit correctly and provide good-enough results, but we cannot make pure SpiceSharp version to work, currently it crashes with this stack trace:
```
SpiceSharp.Algebra.SingularException: 'Singular matrix'
   at SpiceSharp.Algebra.Solve.MarkowitzEntireMatrix`1.FindPivot(Markowitz`1 markowitz, SparseMatrix`1 matrix, Int32 eliminationStep) in C:\src\SpiceSharp-master\SpiceSharp\Algebra\Solve\Markowitz\MarkowitzEntireMatrix.cs:line 109
   at SpiceSharp.Algebra.Solve.Markowitz`1.FindPivot(SparseMatrix`1 matrix, Int32 eliminationStep) in C:\src\SpiceSharp-master\SpiceSharp\Algebra\Solve\Markowitz\Markowitz.cs:line 383
   at SpiceSharp.Algebra.RealSolver.OrderAndFactor() in C:\src\SpiceSharp-master\SpiceSharp\Algebra\Solve\RealSolver.cs:line 297
   at SpiceSharp.Simulations.BaseSimulation.Iterate(Int32 maxIterations) in C:\src\SpiceSharp-master\SpiceSharp\Simulations\Base\BaseSimulation.cs:line 451
   at SpiceSharp.Simulations.BaseSimulation.Op(Int32 maxIterations) in C:\src\SpiceSharp-master\SpiceSharp\Simulations\Base\BaseSimulation.cs:line 236
   at SpiceSharp.Simulations.OP.Execute() in C:\src\SpiceSharp-master\SpiceSharp\Simulations\Implementations\OP\OP.cs:line 29
```

Can you help us with this?

**Comment by svenboulanger** [comment]
Hello again!

I've taken the liberty to take a closer look at your example, and I found the following differences between your Spice#.Parser and Spice# examples. It seems to be mostly an issue of mixing "local" and "global" variables.

When you specify the expressions `bxmExpr` and `buvExpr`, you are using "local" references to `v_vel1` and `v_vel2`, but actually, these variables are not local to the subcircuit, because in the parsed example they are connected to the outside (`v_vel` is connected to either `N2` or `N3`).

A similar problem exists for `buvExpr`, which references a floating node `mss`. A bit further, you used `mss1` and `mss2`.

I changed the code as follows and got a result that I believe will be the same as the parser.

```csharp
public void Run()
{
    var op = new OP("op");
    op.Configurations.Get<BaseConfiguration>().AbsoluteTolerance = 1E-5;
    op.ExportSimulationData += (sender, args) => { Print(args); };
    op.Run(GetCircuit());
}

private void Print(ExportDataEventArgs args)
{
    Console.WriteLine("N1 {0}", args.GetVoltage("N1"));
    Console.WriteLine("X_entry1.msx {0}", args.GetVoltage("msx1"));
    Console.WriteLine("X_entry1.msy {0}", args.GetVoltage("msy1"));
    Console.WriteLine("N2 {0}", args.GetVoltage("N2"));
    Console.WriteLine("X_entry1.mss {0}", args.GetVoltage("mss1"));
    Console.WriteLine("X_entry2.msx {0}", args.GetVoltage("msx2"));
    Console.WriteLine("X_entry2.msy {0}", args.GetVoltage("msy2"));
    Console.WriteLine("N3 {0}", args.GetVoltage("N3"));
    Console.WriteLine("X_entry2.mss {0}", args.GetVoltage("mss2"));
}

private Circuit GetCircuit()
{
    var dc = 0.025;
    var result = new Circuit
    {
        new CurrentSource("I_M", "0", "N1", dc),
    };

    result.Merge(GetSubCircuit(1, "N1", "0", "N2"));
    result.Merge(GetSubCircuit(2, "N1", "0", "N3"));

    return result;
}

private Circuit GetSubCircuit(int circuitId, string m_in, string m_out, string v_vel)
{
    var bxmExpr = circuitId == 1
        ? $"((40*Exp((-0.9)*Log(Abs((V({v_vel}))*0.0181818/6e-06)+1e-12))+90*Exp(((-0.003))*Log(Abs((0.0947059))))-80)*850*V({v_vel})*V({v_vel})/2)"
        : $"((40*Exp((-0.9)*Log(Abs((V({v_vel}))*0.0181818/6e-06)+1e-12))+90*Exp(((-0.003))*Log(Abs((0.105294))))-80)*850*V({v_vel})*V({v_vel})/2)";
    var buvExpr = $"(V(mss{circuitId})/850)/(0.1*0.01)";

    var result = new Circuit
    {
        new VoltageSource($"Vmas{circuitId}", m_in, $"msx{circuitId}", 0),
        new Resistor($"Rmas{circuitId}", $"msx{circuitId}", $"msy{circuitId}", 1e-6),
        new BehavioralVoltageSource($"Bxm{circuitId}", $"msy{circuitId}", m_out, bxmExpr),
        new CurrentControlledVoltageSource($"Hmss{circuitId}", $"mss{circuitId}", "0", $"Vmas{circuitId}", 1),
        new BehavioralCurrentSource($"Buv{circuitId}", "0", v_vel, buvExpr),
        new Resistor($"Ruv{circuitId}", "0", v_vel, 1),
    };

    return result;
}
```

The exact reason why you're getting a `SingularMatrix` exception is because of node `mss`. The node is only used as an input for the behavioral current sources, but is never defined by any other part in the circuit. It is a _floating node_, which means that the node is not fixed to any particular voltage. The simulator encounters a singular matrix because of this and throws the exception.

**Comment by marcin-golebiowski** [comment]
@DZychlinski  I will verify if SpicesharpParser works correctly for your netlist. If it's not, I will publish bug fixes today.

**Comment by marcin-golebiowski** [comment]
@DZychlinski Thank you for your netlist.

**Comment by marcin-golebiowski** [comment]
@DZychlinski I believe there is a bug in the SpiceSharpParser or other place.
I've simulated your final netlist with LTSpice and TopSpice demo and results are somehow little different. 

I'm kindly asking for little time to find the root cause.

/Marcin

**Comment by DZychlinski** [comment]
Hi @marcin-golebiowski and @svenboulanger 

I wanted to give you some more feedback after I'd setup the very same code (inside pure SpiceSharp) with function calls and then get back to you with results I got. Because you already started comparing results between SpiceSharpParser and other Spice implementations, I can also provide results we got from Berkeley Spice 3f5 (I haven't run this simulation myself, but I believe (or hope so) this comes from original BSpice implementation). I'll update results for SpiceSharp with function calls results when I'll get it to work.
```
-----------------------
BSpice 3f5 circuit results:
-----------------------
N1              1,09709206517086
X_entry1.msx    1,09709206517086
X_entry1.msy    1,09709205267879
N2              0,0146965458842177
X_entry1.mss    0,0124920640140771
X_entry2.msx    1,097092060948
X_entry2.msy    1,09709204844006
N3              0,0147152187922527
X_entry2.mss    0,0125079359859228
-----------------------
Parser circuit results:
-----------------------
N1              1,09709008759081
X_entry1.msx    1,09709008759081
X_entry1.msy    1,09709007509082
N2              0,0147058771145686
X_entry1.mss    0,0124999956227839
X_entry2.msx    1,09709008759273
X_entry2.msy    1,09709007509273
N3              0,0147058876089853
X_entry2.mss    0,0125000043772161
-----------------------
String equation circuit results:
-----------------------
N1              1,09709016147817
X_entry1.msx    1,09709016147817
X_entry1.msy    1,09709014897817
N2              0,0147058828519068
X_entry1.mss    0,0125000002793968
X_entry2.msx    1,09709016149282
X_entry2.msy    1,09709014899282
N3              0,0147058822314966
X_entry2.mss    0,0124999997206032
```

**Comment by svenboulanger** [comment]
@DZychlinski and @marcin-golebiowski 

When finding out the reason for these differences, please be aware that a simulator only should produce results that are within a specified tolerance. If you want more accurate results, you may also want to play with these tolerances yourself.

By default, the tolerance is computed using the `RelativeTolerance` and `AbsoluteTolerance` parameters, which are set to `1e-3` and `1e-12` respectively by default. Every iteration, and for each node voltage, an allowed tolerance is computed using the function:

```csharp
tol = Math.Max(Math.Abs(previous_value), Math.Abs(new_value)) * RelativeTolerance + AbsoluteTolerance
```

If the new value is closer to the old value than the computed tolerance, the simulator decides that convergence has been achieved and that it can continue with this solution. If one of the variables has moved more than the computed tolerance, then the simulator will compute another iteration to get a value closer to the _real_ solution.

So for different simulators with the default tolerance settings, you should allow a relative error of about `x 0.001` on all the node voltages. Looking at the simulation outputs by @DZychlinski this seems to be the case.

You can specify a more strict tolerance (eg. `RelativeTolerance = 1e-6`) using a [BaseConfiguration](https://spicesharp.github.io/SpiceSharp/api/SpiceSharp.Simulations.BaseConfiguration.html) for the simulation to get a more accurate result.

**Comment by marcin-golebiowski** [comment]
@svenboulanger @DZychlinski One of the issues in the parser is that `Abs` and `abs` is different function . That will fixed.

**Comment by marcin-golebiowski** [comment]
@svenboulanger After fixing the `Abs` the results are very different.

**Comment by svenboulanger** [comment]
@marcin-golebiowski 
Using Spice#.Parser with the last update of Spice#.Behavior (v1.1.4) gives me

```
N1 1,09709008759081
X_entry1.msx 1,09709008759081
X_entry1.msy 1,09709007509082
N2 0,0147058771145686
X_entry1.mss 0,0124999956227839
X_entry2.msx 1,09709008759273
X_entry2.msy 1,09709007509273
N3 0,0147058876089853
X_entry2.mss 0,0125000043772161
```
This seems to be consistent with previous results.

Can you give more information in what's different and how different?

**Comment by marcin-golebiowski** [comment]
@svenboulanger 
Please run:

public void Run()
{
    var op = new OP("op");
    op.Configurations.Get<BaseConfiguration>().AbsoluteTolerance = 1E-5;
    op.ExportSimulationData += (sender, args) => { Print(args); };
    op.Run(GetCircuit());
}

private void Print(ExportDataEventArgs args)
{
    Console.WriteLine("N1 {0}", args.GetVoltage("N1"));
    Console.WriteLine("X_entry1.msx {0}", args.GetVoltage("msx1"));
    Console.WriteLine("X_entry1.msy {0}", args.GetVoltage("msy1"));
    Console.WriteLine("N2 {0}", args.GetVoltage("N2"));
    Console.WriteLine("X_entry1.mss {0}", args.GetVoltage("mss1"));
    Console.WriteLine("X_entry2.msx {0}", args.GetVoltage("msx2"));
    Console.WriteLine("X_entry2.msy {0}", args.GetVoltage("msy2"));
    Console.WriteLine("N3 {0}", args.GetVoltage("N3"));
    Console.WriteLine("X_entry2.mss {0}", args.GetVoltage("mss2"));
}

private Circuit GetCircuit()
{
    var dc = 0.025;
    var result = new Circuit
    {
        new CurrentSource("I_M", "0", "N1", dc),
    };

    result.Merge(GetSubCircuit(1, "N1", "0", "N2"));
    result.Merge(GetSubCircuit(2, "N1", "0", "N3"));

    return result;
}

private Circuit GetSubCircuit(int circuitId, string m_in, string m_out, string v_vel)
{
    var bxmExpr = circuitId == 1
        ? $"((40*Exp((-0.9)*Log(Abs((V({v_vel}))*0.0181818/6e-06)+1e-12))+90*Exp(((-0.003))*Log(Abs((0.0947059))))-80)*850*V({v_vel})*V({v_vel})/2)"
        : $"((40*Exp((-0.9)*Log(Abs((V({v_vel}))*0.0181818/6e-06)+1e-12))+90*Exp(((-0.003))*Log(Abs((0.105294))))-80)*850*V({v_vel})*V({v_vel})/2)";
    var buvExpr = $"(V(mss{circuitId})/850)/(0.1*0.01)";

    var result = new Circuit
    {
        new VoltageSource($"Vmas{circuitId}", m_in, $"msx{circuitId}", 0),
        new Resistor($"Rmas{circuitId}", $"msx{circuitId}", $"msy{circuitId}", 1e-6),
        new BehavioralVoltageSource($"Bxm{circuitId}", $"msy{circuitId}", m_out, bxmExpr),
        new CurrentControlledVoltageSource($"Hmss{circuitId}", $"mss{circuitId}", "0", $"Vmas{circuitId}", 1),
        new BehavioralCurrentSource($"Buv{circuitId}", "0", v_vel, buvExpr),
        new Resistor($"Ruv{circuitId}", "0", v_vel, 1),
    };

    return result;
}
with latest SpiceSharpBehavioral or in the netlist change function names to have first big letter.

**Comment by marcin-golebiowski** [comment]
@svenboulanger @DZychlinski I think I found the root cause of the problem.
After the PR #21 above program returns results as TopSpice and LTSpice
