### ISSUE TITLE
Pow function does not work in expressions

### ISSUE THREAD

**Issue by rgawry** [SpiceSharp/SpiceSharpBehavioral#3]
I'm using `new BehavioralVoltageSource($"A1", $"out", "0", "Pow(V(in),3)")` and i got error `SpiceSharpBehavioral.Parsers.ParserException: 'Unrecognized method 'Pow()' at character 16 (')')'`

**Comment by svenboulanger** [comment]
Are you providing your own parser to the behavioral source? If you don't specify one, it will provide a standard one with all math functions. If you are providing your own as a parameter, then it will not by default have all the math functions.
