### ISSUE TITLE
Support for PTfudge_factor

### ISSUE THREAD

**Issue by marcin-golebiowski** [SpiceSharp/SpiceSharpBehavioral#5]
Please add ability to specify PTfudge_factor in Pow:

![image](https://user-images.githubusercontent.com/115426/66268629-8ac10500-e83f-11e9-9ea8-862062da90b1.png)

**Comment by svenboulanger** [comment]
I added a fudge factor for division and Pow(). Pow() is now also antisymmetrical like in most other Spice simulators.
