### ISSUE TITLE
BehavioralCapacitor issue

### ISSUE THREAD

**Issue by marcin-golebiowski** [SpiceSharp/SpiceSharpBehavioral#60]
Should this work? I've just replaced Capacitor with BehavioralCapacitor in the test from SpiceSharpTests

It's saying that the C1[v] is 10 in the second export call ...

```
[Test]
        public void When_LowpassRCTransientTrapezoidal_Expect_Reference()
        {
            /*
             * A test for a lowpass RC circuit (DC voltage, resistor, capacitor)
             * The initial voltage on capacitor is 0V. The result should be an exponential converging to dcVoltage.
             */
            double dcVoltage = 10;
            var resistorResistance = 10e3; // 10000;
            var capacitance = 1e-6; // 0.000001;
            var tau = resistorResistance * capacitance;

            // Build circuit
            var ckt = new Circuit(
                new BehavioralCapacitor("C1", "OUT", "0", capacitance.ToString()),
                new Resistor("R1", "IN", "OUT", resistorResistance),
                new VoltageSource("V1", "IN", "0", dcVoltage)
                );

            // Create simulation, exports and references
            var tran = new Transient("tran", 1e-8, 10e-6);
            tran.TimeParameters.InitialConditions["OUT"] = 0.0;
            IExport<double>[] exports = { new RealPropertyExport(tran, "C1", "v") };
            Func<double, double>[] references = { t => dcVoltage * (1.0 - Math.Exp(-t / tau)) };

            // Run
            AnalyzeTransient(tran, ckt, exports, references);
        }
```

**Comment by svenboulanger** [comment]
Yes, this doesn't work (at least at the moment). The reason is that there is no general way to reverse-calculate the charges from a voltage across it from just the expression.

It is straight-forward for linear capacitors, but BehavioralCapacitors can't use that assumption... I know that LTSpice has an additional parameter for `idt()` that allows specifying the initial condition, but Spice#.Behavioral doesn't have this yet.

**Comment by marcin-golebiowski** [comment]
Thanks for reply

**Comment by svenboulanger** [comment]
I found the issue. It should work, but the function specified is the charge and not the capacitance. I.e. You should specify
`C*x`
As the expression, with C = the capacitance value. `x` represents the voltage across the capacitor.

**Comment by marcin-golebiowski** [comment]
Yeap. It works that way. Thanks.
