### ISSUE TITLE
SpiceSharp.SpiceSharpException : Unrecognized variable 2

### ISSUE THREAD

**Issue by marcin-golebiowski** [SpiceSharp/SpiceSharpBehavioral#68]
Hi,

Following tests fails with "SpiceSharp.SpiceSharpException : Unrecognized variable 2" exception.
It seems that `IF(v(2, 0) >= 1, ..., ...)` is causing some problem.

        [Test]
        public void When_If_Expect_Reference()
        {
            var ckt = new Circuit(
                new VoltageSource("V1", "2", "0", 0.5),
                new VoltageSource("V2", "1", "0", 10),
                new BehavioralResistor("RSwitch", "1", "0", "IF(v(2, 0) >= 1, 10, (v(2, 0) <= 0 ? 1000000 : (exp(8.05904782547916 + 3 * -11.5129254649702 * (v(2, 0)-0.5)/(2*1) - 2 * -11.5129254649702 * pow(v(2, 0)-0.5, 3)/(pow(1,3))))))"));
            var op = new OP("Voltage switch simulation");
            var refExport = new RealCurrentExport(op, "V2");
            op.ExportSimulationData += (sender, args) =>
            {
                Assert.AreEqual(-0.00316228, refExport.Value, 1e-8);
            };

            op.Run(ckt);
        }

**Comment by marcin-golebiowski** [comment]
@svenboulanger Am I doing something wrong in `IF` or it's bug in SpiceSharpBehavioral ?

**Comment by svenboulanger** [comment]
This should work as you intend it I think. I'll look into it, but I need a bit of time for it.

**Comment by svenboulanger** [comment]
I have added your test to the project, and it should work as intended now.

It wasn't an easy one. I refactored part of the code as well. Please let me know if something broke :-)

**Comment by marcin-golebiowski** [comment]
It seems that everything is fine according to tests. I'm closing the ticket
