### ISSUE TITLE
Feature request: Introduce additional parameter in IParser<T> Parse method

### ISSUE THREAD

**Issue by marcin-golebiowski** [SpiceSharp/SpiceSharpBehavioral#7]
What:

Please add additional parameter to Parse method: `context` that will be used to pass a reference to simulation.

Why:
At the moment only one parser can be defined for behavioral components. Because of that I found that it's not possible in Spice#.Parser to use that components when multiple simulations are defined. Simulations can have different values of parameters. 

Best regards
Marcin

**Comment by svenboulanger** [comment]
I am unsure of what the context would provide. You can pass each component a different parser if you'd like using the parameter in `SpiceSharpBehavioral.Components.BehavioralBehaviors.BaseParameters`. The parser is unaware of any simulation. That is something that needs to be implemented via events which the component implements.

```csharp
/// <summary>
/// Gets or sets the parser used to parse the expression.
/// </summary>
[ParameterName("parser"), ParameterInfo("The parser that is used to parse the expression")]
public ISpiceDerivativeParser<double> Parser { get; set; }
```

**Comment by marcin-golebiowski** [comment]
In Spice#.Parser all components are shared by multiple simulations. Also the simulations can be run in parallel. It means that either I will make a copy of circuit for each simulation or we found nice and clean solution :)

At the moment I have code like following:

![image](https://user-images.githubusercontent.com/115426/66342284-5df91480-e949-11e9-942e-078f3dee8288.png)

**Comment by svenboulanger** [comment]
Mhmm, but components are only there to create behaviors for each simulation. I agree that the behaviors currently can't be created concurrently if the parser is the same, but then we can just make the parser cloneable instead and make sure the `BaseParameters` are cloned?

**Comment by marcin-golebiowski** [comment]
I think cloning `parser` will be ok. But still I need to have reference to simulation to get proper values of parameters.

**Comment by svenboulanger** [comment]
Alright, then I believe it's best to change the framework structure such that `ISpiceDerivativeParser` is aware of simulations.

**Comment by marcin-golebiowski** [comment]
@svenboulanger Sounds good

**Comment by marcin-golebiowski** [comment]
@svenboulanger ok, no problem, I will focus on different issues in parser.

**Comment by marcin-golebiowski** [comment]
@svenboulanger I think it would better to define factory of parsers and assign it to the entity.
Enitity behaviours would create parsers using that factory. Having factory enables to define derived factories for specific simulation.
